version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "daily"
      time: "16:00"
    groups:
      pip-security-updates:
        applies-to: security-updates
        patterns:
          - "*"
      pip-version-updates:
        applies-to: version-updates
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "daily"
      time: "16:00"
    groups:
      github-actions:
        patterns:
          - "*"
