version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      time: "16:10"
    target-branch: "dev"
    groups:
      pip-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "daily"
      time: "16:00"
    groups:
      github-actions:
        patterns:
          - "*"
