name: Pre-commit auto-update

on:
  # every 15 minutes
  # schedule:
  #   - cron: "*/15 * * * *"
  # on demand
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  upgrade:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: dev

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      - name: Update pre-commit hooks
        run: |
          pre-commit autoupdate

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}
          commit-message: "chore(deps): upgrade pre-commit hooks"
          title: "chore(deps): upgrade pre-commit hooks"
          body: |
            ## Pre-commit Hooks Update

            This PR updates the pre-commit hooks to their latest versions.

            ### Changes
            - Updated pre-commit hooks to latest available versions
            - Auto-generated by GitHub Actions

            ### Checklist
            - [ ] Review the changes
            - [ ] Test the updated hooks locally
            - [ ] Merge if everything looks good

            ---
            *This PR was automatically created by the pre-commit auto-update workflow*
          branch: update/pre-commit-hooks
          branch-suffix: timestamp
          base: dev
          delete-branch: true
